### PR TITLE
fix: run po for longtask only once

### PR DESCRIPTION
**Pull request by SuperOleg39**

### CODE REVIEW

**Review by Zizzamia — APPROVED** [review]
Great catch!!!!!!!

**Comment by Zizzamia** [comment]
Thank you for this huge fix!

**Comment by Zizzamia** [comment]
@SuperOleg39 if you have a minute, would you mind have a PR with tests as well, please.

**Comment by SuperOleg39** [comment]
>  if you have a minute, would you mind have a PR with tests as well, please.

Wiil try! This case looks like more for some integration in-browser test, but maybe units will be enought, need to check

**Comment by SuperOleg39** [comment]
@Zizzamia ready https://github.com/Zizzamia/perfume.js/pull/217

**Pull request merged**
