### PR TITLE
feat: timeToInteractive as promise

### PR DESCRIPTION
**Pull request by lorenzodianni**
Example:

```js
const instance = new Perfume({timeToInteractive: true});

instance.waitUntilTimeToInteractive().then((time) => {
  console.log(`${time}ms`)
});
```

### CODE REVIEW

**Comment by lorenzodianni** [comment]
Ciao Leonardo, ieri ero al MilanoJS ed ho colto l'occasione per fare la pull request ;)

**Comment by lorenzodianni** [comment]
Ciao @Zizzamia, no problem, i'll do these changes ASAP ;) 
My twitter account is `@lorenzodianni`, thanks!

**Comment by lorenzodianni** [comment]
I've just changed the promise name and did some little improvements 🎉

## Docs
`timeToInteractiveDuration` is **not** deprecated, if you want you can use it inside a timeout, like you did before the promise. This feature doesn't introduce breaking changes.
We should just integrate it in the documentation.

## Refactoring
Yeah, absolutely 💪 
<br/>
I can do both (*docs*/*refactoring*), let me know as you wish 🕺

**Comment by Zizzamia** [comment]
🔥🚀🌕

**Comment by Zizzamia** [comment]
@lorenzodianni Grazie ancora
https://twitter.com/Zizzamia/status/987282173198774273

**Comment by lorenzodianni** [comment]
Grazie a te!!! 🎉 🎉 🎉 

Just one more thing:
this new feature introduce a promise, so:
```
// right
perfume.observeTimeToInteractive().then((tti) => {
  console.log(tti)
})

// wrong
perfume.observeTimeToInteractive((tti) => {
  console.log(tti)
})
```

Just to be clear because I saw on tweet the example that you wrote and it's not a promise 😉 
___

I'd like to do some more pull requests for refactoring tests and docs, what do you think?

**Comment by Zizzamia** [comment]
Ops, wrong tweet!
And go ahead with the PRs 👊
I will release Perfume v0.7.0 early next week 🚀

If you have a way to test Perfume on IE11 and Edge that would be really helpful 💯

**Pull request merged**
