### PR TITLE
fix: 'PerformanceObserver is undefined' on Edge

### PR DESCRIPTION
**Pull request by michaeldfallen**
Edge exposes `window.chrome`, meaning that using `Boolean(window.chrome)` to test for the browser being chrome alone is not enough.

To fix this I've also tested for the existence of PerformanceObserver on window so that we only try to use PerformanceObserver if it is defined.

### CODE REVIEW

**Comment by michaeldfallen** [comment]
@Zizzamia can you review?

**Comment by Zizzamia** [comment]
Amazing, coming up soon with v0.8.0
🔥 🚀 🌕

Grazie Mille 🙏

**Comment by michaeldfallen** [comment]
🙌Woo, thanks!

**Comment by Zizzamia** [comment]
@michaeldfallen   released Perfume.js [v0.8.0](https://github.com/Zizzamia/perfume.js/releases/tag/v0.8.0)
Grazie mille for your contribution 🙌

**Pull request merged**
